
version: '3'

networks:
  elasticsearch-network:

services:

  elasticsearch:
    container_name: elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:8.13.1
    ports:
      - 9200:9200
    networks: 
      - elasticsearch-network
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    volumes:
      - elasticsearch-volume:/usr/share/elasticsearch/data
    
  kibana:
    container_name: kibana
    image: docker.elastic.co/kibana/kibana:8.13.1
    ports:
      - 5601:5601
    networks:
      - elasticsearch-network
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    depends_on:
      - elasticsearch
    
volumes:
  elasticsearch-volume:
    